/**
	# fault C construction context environment support.
*/
#ifndef _FAULT_LIBC_H_
#define _FAULT_LIBC_H_

#define _CPP_QUOTE(x) #x
#define STRING_FROM_IDENTIFIER(X) _CPP_QUOTE(X)
#define CONCAT_IDENTIFIER(X, Y) X##Y
#define CONCAT_REFERENCES(X, Y) CONCAT_IDENTIFIER(X,Y)

#define F_TARGET_ARCHITECTURE_STR STRING_FROM_IDENTIFIER(F_TARGET_ARCHITECTURE)
#define F_SYSTEM_STR STRING_FROM_IDENTIFIER(F_SYSTEM)

#define FACTOR_QNAME_STR STRING_FROM_IDENTIFIER(FACTOR_QNAME)
#define FACTOR_BASENAME_STR STRING_FROM_IDENTIFIER(FACTOR_BASENAME)
#define FACTOR_PACKAGE_STR STRING_FROM_IDENTIFIER(FACTOR_PACKAGE)
#define FACTOR_PATH(NAME) FACTOR_QNAME_STR "." NAME

#ifndef F_INTENTION
	#warning Compiler was not given an F_INTENTION preprocessor definition; presuming 'optimal'.
	#define F_INTENTION optimal
#endif

#define F_INTENTION_STR STRING_FROM_IDENTIFIER(F_INTENTION)

#define F_INTENTION_optimal 1
#define F_INTENTION_debug 2

#define F_INTENTION_injections 5
#define F_INTENTION_instruments 10

#define F_INTENTION_profiling 4

#define F_INTENTION_fragments (-1)

#define _F_INTENTION_PREFIX() F_INTENTION_
#define _F_INTENTION_REF() F_INTENTION
#undef F_INTENTION_ID
#define F_INTENTION_ID CONCAT_REFERENCES(_F_INTENTION_PREFIX(),_F_INTENTION_REF())

#define F_TRACE(y) 0

#define FV_OPTIMAL(y) (F_INTENTION_ID == F_INTENTION_optimal)
#define FV_DEBUG(y) (F_INTENTION_ID == F_INTENTION_debug)

#define FV_INJECTIONS(y) \
	(F_INTENTION_ID == F_INTENTION_injections || F_INTENTION_ID == F_INTENTION_instruments)
#define FV_INSTRUMENTS(y) (F_INTENTION_ID == F_INTENTION_instruments)

#define FV_COVERAGE(y) (F_INTENTION_ID == F_INTENTION_coverage)
#define FV_PROFILING(y) (F_INTENTION_ID == F_INTENTION_profiling)

#define FV_FRAGMENTS(y) (F_INTENTION_ID == F_INTENTION_fragments)

#endif /* guard */
